# Домашнее задание 5

Перед выполнением заданий необходимо сохранить копию этого блокнота себе на диск. Или скачать `.ipynb`/`.py` файл для локальной разработки.

За работу можно получить максимум 8 баллов.

## Полным полна коробочка (1 балл)


Создайте список, содержащий: вектор, матрицу и подсписок.
Обратитесь к элементам списка разными способами ($, [[ ]], [ ]).
Измените один элемент в подсписке.

In [ ]:
v <- c(1, 2, 3)
m <- matrix(1:6, nrow = 2)
s <- list(a = 10, b = 20)

L <- list(vec = v, mt = m, slist = s)
L$vec
L[["m"]]
L[1]
L[[1]]
L$slist$b <- 999
L$slist

[1] 1 2 3

NULL

$vec
[1] 1 2 3

[1] 1 2 3

$a
[1] 10

$b
[1] 999

## Матрицы атакуют (1 балл)

Найти решение системы

$$
\begin{equation}
\begin{cases}
\xi_1 & + & 2 \xi_2 & + & 3 \xi_3 & + & 4 \xi_4 & + & 5 \xi_5 & = & 2
\\
2\xi_1 & + & 3 \xi_2 & + & 7 \xi_3 & + & 10 \xi_4 & + & 13 \xi_5 & = & 12
\\
3\xi_1 & + & 5 \xi_2 & + & 11 \xi_3 & + & 16 \xi_4 & + & 21 \xi_5 & = & 17
\\
2\xi_1 & - & 7 \xi_2 & + & 7 \xi_3 & + & 7 \xi_4 & + & 2 \xi_5 & = & 57
\\
\xi_1 & + & 4 \xi_2 & + & 5 \xi_3 & + & 3 \xi_4 & + & 10 \xi_5 & = & 7
\end{cases}
\end{equation}
$$

PS: используйте встроенные в R функции решения систем.

In [ ]:
A <- matrix(c(
  1,  2,  3,  4,  5,
  2,  3,  7, 10, 13,
  3,  5, 11, 16, 21,
  2, -7,  7,  7,  2,
  1,  4,  5,  3, 10
), nrow = 5, byrow = TRUE)
b <- c(2, 12, 17, 57, 7)
solve(A, b)

[1]  3 -5  4 -2  1

## Снова матрицы (1 балл)

Создайте матрицу 5 на 5, заполнив ее произвольными числами.

* выведите элемент из третей строки и четвертого столбца
* замените значения второго столбца на ваш номер ИСУ без первой цифры
* вычислить сумму значений по каждой строке и каюдому столбцу

Рекомендуем для проверки выводить в консоль промежуточные значения матрицы.

In [ ]:
set.seed(1)
M <- matrix(sample(1:50, 25, replace = TRUE), nrow = 5)
M
M[3, 4]
M[, 2] <- c(0, 1, 1, 8, 2)
M
rowSums(M)
colSums(M)

     [,1] [,2] [,3] [,4] [,5]
[1,]  4   43   21    9   25
[2,] 39   14   42   15   46
[3,]  1   18   46   21   37
[4,] 34   33   10   37   37
[5,] 23   21    7   41   34

[1] 21

     [,1] [,2] [,3] [,4] [,5]
[1,]  4   0    21    9   25
[2,] 39   1    42   15   46
[3,]  1   1    46   21   37
[4,] 34   8    10   37   37
[5,] 23   2     7   41   34

[1]  59 143 106 126 107

[1] 101  12 126 123 179

## Потерянные списки (1 балл)

В классе учатся `n` школьников. Известно, что некоторые из них участвовали в олимпиадах:
* `a` школьников участвовали в олимпиаде по математике
* `b` школьников - по информатике
* `c` школьников - по информатике

Однако, преподаватель потерял списки участников по каждому из предметов. Помогите учителю определить, сколько школьников могло не участвовать ни в какой олимпиаде. Выведите наибольшее и наименьшее возможное число таких.

Пример ввода:
```
10
7
5
3
```

Пример вывода:
```
0
3
```

In [ ]:
n <- as.integer(readline(prompt="общее число: "))
a <- as.integer(readline(prompt="число участников математики: "))
b <- as.integer(readline(prompt="число участников информатики b: "))
c <- as.integer(readline(prompt="число участников ещё одного предмета c: "))
T <- a + b + c
U_min <- max(max(a,b,c), ceiling(T/3))
U_max <- min(n, T)
max_none <- n - U_min
min_none <- n - U_max

cat("наибольшее:", max_none, "\n")
cat("наименьшее:", min_none, "\n")

общее число: 6
число участников математики: 8
число участников информатики b: 5
число участников ещё одного предмета c: 0
наибольшее: -2
наименьшее: 0

## Сложные узоры (2 балла)

Создайте матрицу 10×10 из случайных чисел.
Замените все элементы, стоящие ниже главной диагонали, на 0.
Затем замените все элементы выше диагонали на среднее значение по диагонали.

In [ ]:
set.seed(1)
M <- matrix(runif(100), nrow = 10)
M
M[lower.tri(M)] <- 0
M
d <- mean(diag(M))
M[upper.tri(M)] <- d
M

      [,1]       [,2]      [,3]       [,4]      [,5]      [,6]       [,7]
 [1,] 0.26550866 0.2059746 0.93470523 0.4820801 0.8209463 0.47761962 0.91287592
 [2,] 0.37212390 0.1765568 0.21214252 0.5995658 0.6470602 0.86120948 0.29360337
 [3,] 0.57285336 0.6870228 0.65167377 0.4935413 0.7829328 0.43809711 0.45906573
 [4,] 0.90820779 0.3841037 0.12555510 0.1862176 0.5530363 0.24479728 0.33239467
 [5,] 0.20168193 0.7698414 0.26722067 0.8273733 0.5297196 0.07067905 0.65087047
 [6,] 0.89838968 0.4976992 0.38611409 0.6684667 0.7893562 0.09946616 0.25801678
 [7,] 0.94467527 0.7176185 0.01339033 0.7942399 0.0233312 0.31627171 0.47854525
 [8,] 0.66079779 0.9919061 0.38238796 0.1079436 0.4772301 0.51863426 0.76631067
 [9,] 0.62911404 0.3800352 0.86969085 0.7237109 0.7323137 0.66200508 0.08424691
[10,] 0.06178627 0.7774452 0.34034900 0.4112744 0.6927316 0.40683019 0.87532133
      [,8]      [,9]      [,10]
 [1,] 0.3390729 0.4346595 0.23962942
 [2,] 0.8394404 0.7125147 0.05893438
 [3,] 0.3466835 0.3999944 0.64228826
 [4,] 0.3337749 0.3253522 0.87626921
 [5,] 0.4763512 0.7570871 0.77891468
 [6,] 0.8921983 0.2026923 0.79730883
 [7,] 0.8643395 0.7111212 0.45527445
 [8,] 0.3899895 0.1216919 0.41008408
 [9,] 0.7773207 0.2454885 0.81087024
[10,] 0.9606180 0.1433044 0.60493329

      [,1]      [,2]      [,3]      [,4]      [,5]      [,6]       [,7]
 [1,] 0.2655087 0.2059746 0.9347052 0.4820801 0.8209463 0.47761962 0.9128759
 [2,] 0.0000000 0.1765568 0.2121425 0.5995658 0.6470602 0.86120948 0.2936034
 [3,] 0.0000000 0.0000000 0.6516738 0.4935413 0.7829328 0.43809711 0.4590657
 [4,] 0.0000000 0.0000000 0.0000000 0.1862176 0.5530363 0.24479728 0.3323947
 [5,] 0.0000000 0.0000000 0.0000000 0.0000000 0.5297196 0.07067905 0.6508705
 [6,] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.09946616 0.2580168
 [7,] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.00000000 0.4785452
 [8,] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.00000000 0.0000000
 [9,] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.00000000 0.0000000
[10,] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.00000000 0.0000000
      [,8]      [,9]      [,10]
 [1,] 0.3390729 0.4346595 0.23962942
 [2,] 0.8394404 0.7125147 0.05893438
 [3,] 0.3466835 0.3999944 0.64228826
 [4,] 0.3337749 0.3253522 0.87626921
 [5,] 0.4763512 0.7570871 0.77891468
 [6,] 0.8921983 0.2026923 0.79730883
 [7,] 0.8643395 0.7111212 0.45527445
 [8,] 0.3899895 0.1216919 0.41008408
 [9,] 0.0000000 0.2454885 0.81087024
[10,] 0.0000000 0.0000000 0.60493329

      [,1]      [,2]      [,3]      [,4]      [,5]      [,6]       [,7]
 [1,] 0.2655087 0.3628099 0.3628099 0.3628099 0.3628099 0.36280991 0.3628099
 [2,] 0.0000000 0.1765568 0.3628099 0.3628099 0.3628099 0.36280991 0.3628099
 [3,] 0.0000000 0.0000000 0.6516738 0.3628099 0.3628099 0.36280991 0.3628099
 [4,] 0.0000000 0.0000000 0.0000000 0.1862176 0.3628099 0.36280991 0.3628099
 [5,] 0.0000000 0.0000000 0.0000000 0.0000000 0.5297196 0.36280991 0.3628099
 [6,] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.09946616 0.3628099
 [7,] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.00000000 0.4785452
 [8,] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.00000000 0.0000000
 [9,] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.00000000 0.0000000
[10,] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.00000000 0.0000000
      [,8]      [,9]      [,10]
 [1,] 0.3628099 0.3628099 0.3628099
 [2,] 0.3628099 0.3628099 0.3628099
 [3,] 0.3628099 0.3628099 0.3628099
 [4,] 0.3628099 0.3628099 0.3628099
 [5,] 0.3628099 0.3628099 0.3628099
 [6,] 0.3628099 0.3628099 0.3628099
 [7,] 0.3628099 0.3628099 0.3628099
 [8,] 0.3899895 0.3628099 0.3628099
 [9,] 0.0000000 0.2454885 0.3628099
[10,] 0.0000000 0.0000000 0.6049333

## Магическое число (2 балла)

Согласно определению предела последовательности
$$
A = \lim\limits_{n\to\infty} x_n :=
\forall\varepsilon > 0 ~~ \exists N \in\mathbb{N} : \forall n > N ~~ |x_n - A| < \varepsilon
$$

Петя решил найти этот номер `N` для некоторых $\varepsilon$. Для последовательности
$$
y_n = \frac{n+5}{n+2} \arccos{\sqrt{\frac{2+(-1)^n}{4}}}
$$

при $\varepsilon = 0.01$, $\varepsilon = 0.001$ найти такие номера `N`, начиная с которых становится верным неравенство $|x_n - A| < \varepsilon$.

Для тех, чей номер ИСУ заканчивается четной цифрой, использовать $A = \frac{\pi}{3}$ и последовательность $x_n = y_{2n}$

Для тех, чей номер ИСУ заканчивается нечетной цифрой, использовать $A = \frac{\pi}{6}$ и последовательность $x_n = y_{2n-1}$


При решениии можете использовать векторные вычисления или цикл `for`.

In [ ]:

e <- c(0.01, 0.001)
A <- pi/6
find_N <- function(e) {
  n <- 1
  repeat {
    x_n <- (2*n + 5)/(2*n + 2) * acos(sqrt((2 + (-1)^(2*n))/4))
    if (abs(x_n - A) < e) return(n)
    n <- n + 1
  }
}
N_results <- sapply(e, find_N)
names(N_results) <- paste0("e=", e)
N_results

 e=0.01 e=0.001
     78     785

## Строим зиккурат! (2 балла)

Напишите функцию, которая принимает одно целое число `n`, и возвращает пронумерованные этажи зиккурата. Представим, что мы смотрим на зиккурат сверху вниз. Этажи зиккурата нумеруются с первого, ширина каждой ступеньки равна одной строке или столбцу.

Пример ввода:
```
4
```

Пример вывода:
```
1  1  1  1  1  1  1
1  2  2  2  2  2  1
1  2  3  3  3  2  1
1  2  3  4  3  2  1
1  2  3  3  3  2  1
1  2  2  2  2  2  1
1  1  1  1  1  1  1
```

In [ ]:
n <- as.integer(readline())
z <- function(n) {
  size <- 2*n - 1
  mat <- matrix(0, nrow = size, ncol = size)

  for (i in 1:size) {
    for (j in 1:size) {
      mat[i, j] <- 1 + min(i-1, j-1, size-i, size-j)
    }
  }

  return(mat)
}
result <- z(n)
for (i in 1:nrow(result)) {
  cat(result[i, ], "\n")
}

8
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 2 2 2 2 2 2 2 2 2 2 2 2 2 1
1 2 3 3 3 3 3 3 3 3 3 3 3 2 1
1 2 3 4 4 4 4 4 4 4 4 4 3 2 1
1 2 3 4 5 5 5 5 5 5 5 4 3 2 1
1 2 3 4 5 6 6 6 6 6 5 4 3 2 1
1 2 3 4 5 6 7 7 7 6 5 4 3 2 1
1 2 3 4 5 6 7 8 7 6 5 4 3 2 1
1 2 3 4 5 6 7 7 7 6 5 4 3 2 1
1 2 3 4 5 6 6 6 6 6 5 4 3 2 1
1 2 3 4 5 5 5 5 5 5 5 4 3 2 1
1 2 3 4 4 4 4 4 4 4 4 4 3 2 1
1 2 3 3 3 3 3 3 3 3 3 3 3 2 1
1 2 2 2 2 2 2 2 2 2 2 2 2 2 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

## Пишем Counter на R (2 балла)

В питоне есть структура `Counter`, которая на заданном наборе данных создает словарь, в котором по каждому элементу хранит информацию о том сколько данное числов встретилось в наборе.

Вам необходимо реализовать похожу функцию, но без создания структуры. Пусть дан целочисленный вектор `x`. Вам необходимо вывести информацию о том, какой элемент сколько раз встретился в этом векторе. Элементы должны быть упорядочены по возрастанию.

Так, для вектора
```R
x <- c(5, 2, 7, 7, 7, 2, 0, 0)
```

вам нужно вывести

Пример вывода:
```
0 2 5 7
2 2 1 3
```

In [ ]:
x <- as.integer(unlist(strsplit(readline(), " ")))
us <- sort(unique(x))
c <- sapply(us, function(val) sum(x == val))
cat(us, "\n")
cat(c, "\n")

8 9 5
5 8 9
1 1 1